name: CI Angular app through Github Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Setup
        run: npm ci
      - name: build
        run: npm run build
      - name: Test
        run:  npm run test 
